# Generated by Django 5.2.7 on 2025-10-05 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('hospital_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('medicine_details', models.TextField(blank=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
