# Generated by Django 5.2.7 on 2025-10-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patienttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttask',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
