# Generated by Django 5.2.7 on 2025-10-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patienttask_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='therapist_notes',
            field=models.TextField(blank=True),
        ),
    ]
