# Generated by Django 5.2.7 on 2025-10-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patienttask_started_at_patienttask_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttask',
            name='task_type',
            field=models.CharField(choices=[('adaptive_sports', 'Adaptive Sports'), ('creative_arts', 'Creative Arts'), ('music_therapy', 'Music Therapy'), ('speech_therapy', 'Speech Therapy'), ('exercise', 'Exercise'), ('yoga', 'Yoga'), ('sensory_play', 'Sensory Play'), ('social_skills', 'Social Skills Training'), ('language_learning', 'Language Learning'), ('gardening', 'Gardening')], default='exercise', max_length=30),
        ),
    ]
