# Generated by Django 5.2.7 on 2025-10-08 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='doctor',
            field=models.ForeignKey(default=12, limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='visits_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
