# Generated by Django 5.2.7 on 2025-10-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patientvisit_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='summary',
            field=models.TextField(blank=True, help_text='Auto-generated summary of visit for dashboard preview', null=True),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text="Doctor's observations and recommendations for next visit", null=True),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='improvement_score',
            field=models.PositiveIntegerField(default=0, help_text='Percentage improvement compared to previous visit (0–100)'),
        ),
    ]
