# Generated by Django 5.2.7 on 2025-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_date_of_birth_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
