# Generated by Django 5.2.8 on 2025-11-18 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sosalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('exercise_type', models.CharField(choices=[('adaptive_sports', 'Adaptive Sports'), ('creative_arts', 'Creative Arts'), ('music_therapy', 'Music Therapy'), ('speech_therapy', 'Speech Therapy'), ('exercise', 'Exercise'), ('yoga', 'Yoga'), ('sensory_play', 'Sensory Play'), ('social_skills', 'Social Skills Training'), ('language_learning', 'Language Learning'), ('gardening', 'Gardening'), ('physiotherapy', 'Physiotherapy'), ('occupational_therapy', 'Occupational Therapy')], default='exercise', max_length=30)),
                ('video_file', models.FileField(help_text='Upload video file (MP4, AVI, MOV, etc.)', upload_to='exercise_videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image', null=True, upload_to='video_thumbnails/')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from patients')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise Video',
                'verbose_name_plural': 'Exercise Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
